//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOC20.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AOC20.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1348
        ///1621
        ///1500
        ///1818
        ///1266
        ///1449
        ///1880
        ///1416
        ///1862
        ///1665
        ///1588
        ///1704
        ///1922
        ///1482
        ///1679
        ///1263
        ///1137
        ///1045
        ///1405
        ///1048
        ///1619
        ///1520
        ///455
        ///1142
        ///1415
        ///1554
        ///1690
        ///1886
        ///1891
        ///1701
        ///1915
        ///1521
        ///1253
        ///1580
        ///1376
        ///1564
        ///1747
        ///1814
        ///1749
        ///1485
        ///1969
        ///974
        ///1566
        ///1413
        ///1451
        ///1200
        ///1558
        ///1756
        ///1910
        ///1044
        ///470
        ///1620
        ///1772
        ///1066
        ///1261
        ///1776
        ///988
        ///1976
        ///1834
        ///1896
        ///1646
        ///1626
        ///1300
        ///1692
        ///1204
        ///2006
        ///1265
        ///1911
        ///1361
        ///1766
        ///1750
        ///2000
        ///1824
        ///1726
        ///1672
        ///651
        ///1226
        ///1954
        ///1055
        ///1999
        ///1793
        ///1640
        ///1567
        ///1040
        ///1426
        ///1717
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
    }
}
